name: "build"

on:
  push:
    branches:
      - main
      - 2.x
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - 2.x

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          args: --src . ci --ci --version ${{ github.ref_name }} --code-cove-token env:CODECOV_TOKEN --git-token env:GITHUB_TOKEN
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}